artifacts_root: artifacts


data_ingestion:
  datasource: opus_books
  lang_src: en
  lang_tgt: fr
  save_dir: artifacts/opus_books


build_tokenizer:
  data_dir: artifacts/opus_books
  src_lang: en
  tgt_lang: fr
  tokenizer_file: "artifacts/tokenizer_{0}.json"

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/opus_books
  tokenizer_file: "tokenizer_{0}.json"

